// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxfAz3Z7__Xia_eAVmi-xb1K9lqVOuvE',
    appId: '1:203348713632:android:485b1a755b9f3c802c29c5',
    messagingSenderId: '203348713632',
    projectId: 'social-media-f2519',
    storageBucket: 'social-media-f2519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB708yP2zmPRQk7iaDBp8BYoM7m1BoSPKE',
    appId: '1:203348713632:ios:062a47995c4008202c29c5',
    messagingSenderId: '203348713632',
    projectId: 'social-media-f2519',
    storageBucket: 'social-media-f2519.appspot.com',
    androidClientId: '203348713632-c0s12da1qsbtr6f9mjj968bvot84st7e.apps.googleusercontent.com',
    iosClientId: '203348713632-r7ffscppckq6qva8jnq52du5m33jb4e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
